//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSlateDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GSlateEntities : DbContext
    {
        public GSlateEntities()
            : base("name=GSlateEntities")
        {
            Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_PROJECT> TBL_PROJECT { get; set; }
        public virtual DbSet<TBL_USER> TBL_USER { get; set; }
        public virtual DbSet<TBL_USER_PROJECT> TBL_USER_PROJECT { get; set; }
    
        public virtual int CRE_PROJECT_PR(Nullable<int> p_ID, Nullable<System.DateTime> p_START_DATE, Nullable<System.DateTime> p_END_DATE, Nullable<int> p_CREDITS)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("P_ID", p_ID) :
                new ObjectParameter("P_ID", typeof(int));
    
            var p_START_DATEParameter = p_START_DATE.HasValue ?
                new ObjectParameter("P_START_DATE", p_START_DATE) :
                new ObjectParameter("P_START_DATE", typeof(System.DateTime));
    
            var p_END_DATEParameter = p_END_DATE.HasValue ?
                new ObjectParameter("P_END_DATE", p_END_DATE) :
                new ObjectParameter("P_END_DATE", typeof(System.DateTime));
    
            var p_CREDITSParameter = p_CREDITS.HasValue ?
                new ObjectParameter("P_CREDITS", p_CREDITS) :
                new ObjectParameter("P_CREDITS", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CRE_PROJECT_PR", p_IDParameter, p_START_DATEParameter, p_END_DATEParameter, p_CREDITSParameter);
        }
    
        public virtual int CRE_USER_PR(Nullable<int> p_ID, string p_FIRST_NAME, string p_LAST_NAME)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("P_ID", p_ID) :
                new ObjectParameter("P_ID", typeof(int));
    
            var p_FIRST_NAMEParameter = p_FIRST_NAME != null ?
                new ObjectParameter("P_FIRST_NAME", p_FIRST_NAME) :
                new ObjectParameter("P_FIRST_NAME", typeof(string));
    
            var p_LAST_NAMEParameter = p_LAST_NAME != null ?
                new ObjectParameter("P_LAST_NAME", p_LAST_NAME) :
                new ObjectParameter("P_LAST_NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CRE_USER_PR", p_IDParameter, p_FIRST_NAMEParameter, p_LAST_NAMEParameter);
        }
    
        public virtual int CRE_USER_PROJECT_PR(Nullable<int> p_USER_ID, Nullable<int> p_PROJECT_ID, Nullable<System.DateTime> p_ASSIGNED_DATE)
        {
            var p_USER_IDParameter = p_USER_ID.HasValue ?
                new ObjectParameter("P_USER_ID", p_USER_ID) :
                new ObjectParameter("P_USER_ID", typeof(int));
    
            var p_PROJECT_IDParameter = p_PROJECT_ID.HasValue ?
                new ObjectParameter("P_PROJECT_ID", p_PROJECT_ID) :
                new ObjectParameter("P_PROJECT_ID", typeof(int));
    
            var p_ASSIGNED_DATEParameter = p_ASSIGNED_DATE.HasValue ?
                new ObjectParameter("P_ASSIGNED_DATE", p_ASSIGNED_DATE) :
                new ObjectParameter("P_ASSIGNED_DATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CRE_USER_PROJECT_PR", p_USER_IDParameter, p_PROJECT_IDParameter, p_ASSIGNED_DATEParameter);
        }
    
        public virtual int DEL_PROJECT_PR(Nullable<int> p_ID)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("P_ID", p_ID) :
                new ObjectParameter("P_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DEL_PROJECT_PR", p_IDParameter);
        }
    
        public virtual int DEL_USER_PR(Nullable<int> p_ID)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("P_ID", p_ID) :
                new ObjectParameter("P_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DEL_USER_PR", p_IDParameter);
        }
    
        public virtual int DEL_USER_PROJECT_PR(Nullable<int> p_USER_ID, Nullable<int> p_PROJECT_ID)
        {
            var p_USER_IDParameter = p_USER_ID.HasValue ?
                new ObjectParameter("P_USER_ID", p_USER_ID) :
                new ObjectParameter("P_USER_ID", typeof(int));
    
            var p_PROJECT_IDParameter = p_PROJECT_ID.HasValue ?
                new ObjectParameter("P_PROJECT_ID", p_PROJECT_ID) :
                new ObjectParameter("P_PROJECT_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DEL_USER_PROJECT_PR", p_USER_IDParameter, p_PROJECT_IDParameter);
        }
    
        public virtual ObjectResult<RET_ALL_PROJECTS_PR_Result> RET_ALL_PROJECTS_PR()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RET_ALL_PROJECTS_PR_Result>("RET_ALL_PROJECTS_PR");
        }
    
        public virtual ObjectResult<RET_ALL_USER_PROJECTS_PR_Result> RET_ALL_USER_PROJECTS_PR()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RET_ALL_USER_PROJECTS_PR_Result>("RET_ALL_USER_PROJECTS_PR");
        }
    
        public virtual ObjectResult<RET_ALL_USERS_PR_Result> RET_ALL_USERS_PR()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RET_ALL_USERS_PR_Result>("RET_ALL_USERS_PR");
        }
    
        public virtual ObjectResult<RET_PROJECT_PR_Result> RET_PROJECT_PR(Nullable<int> p_ID)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("P_ID", p_ID) :
                new ObjectParameter("P_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RET_PROJECT_PR_Result>("RET_PROJECT_PR", p_IDParameter);
        }
    
        public virtual ObjectResult<RET_USER_PR_Result> RET_USER_PR(Nullable<int> p_USER_ID)
        {
            var p_USER_IDParameter = p_USER_ID.HasValue ?
                new ObjectParameter("P_USER_ID", p_USER_ID) :
                new ObjectParameter("P_USER_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RET_USER_PR_Result>("RET_USER_PR", p_USER_IDParameter);
        }
    
        public virtual ObjectResult<RET_USER_PROJECT_PR_Result> RET_USER_PROJECT_PR(Nullable<int> p_USER_ID, Nullable<int> p_PROJECT_ID)
        {
            var p_USER_IDParameter = p_USER_ID.HasValue ?
                new ObjectParameter("P_USER_ID", p_USER_ID) :
                new ObjectParameter("P_USER_ID", typeof(int));
    
            var p_PROJECT_IDParameter = p_PROJECT_ID.HasValue ?
                new ObjectParameter("P_PROJECT_ID", p_PROJECT_ID) :
                new ObjectParameter("P_PROJECT_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RET_USER_PROJECT_PR_Result>("RET_USER_PROJECT_PR", p_USER_IDParameter, p_PROJECT_IDParameter);
        }
    
        public virtual int UPD_PROJECT_PR(Nullable<int> p_ID, Nullable<System.DateTime> p_START_DATE, Nullable<System.DateTime> p_END_DATE, Nullable<int> p_CREDITS)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("P_ID", p_ID) :
                new ObjectParameter("P_ID", typeof(int));
    
            var p_START_DATEParameter = p_START_DATE.HasValue ?
                new ObjectParameter("P_START_DATE", p_START_DATE) :
                new ObjectParameter("P_START_DATE", typeof(System.DateTime));
    
            var p_END_DATEParameter = p_END_DATE.HasValue ?
                new ObjectParameter("P_END_DATE", p_END_DATE) :
                new ObjectParameter("P_END_DATE", typeof(System.DateTime));
    
            var p_CREDITSParameter = p_CREDITS.HasValue ?
                new ObjectParameter("P_CREDITS", p_CREDITS) :
                new ObjectParameter("P_CREDITS", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPD_PROJECT_PR", p_IDParameter, p_START_DATEParameter, p_END_DATEParameter, p_CREDITSParameter);
        }
    
        public virtual int UPD_USER_PR(Nullable<int> p_ID, string p_FIRST_NAME, string p_LAST_NAME)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("P_ID", p_ID) :
                new ObjectParameter("P_ID", typeof(int));
    
            var p_FIRST_NAMEParameter = p_FIRST_NAME != null ?
                new ObjectParameter("P_FIRST_NAME", p_FIRST_NAME) :
                new ObjectParameter("P_FIRST_NAME", typeof(string));
    
            var p_LAST_NAMEParameter = p_LAST_NAME != null ?
                new ObjectParameter("P_LAST_NAME", p_LAST_NAME) :
                new ObjectParameter("P_LAST_NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPD_USER_PR", p_IDParameter, p_FIRST_NAMEParameter, p_LAST_NAMEParameter);
        }
    
        public virtual int UPD_USER_PROJECT_PR(Nullable<int> p_USER_ID, Nullable<int> p_PROJECT_ID, Nullable<bool> p_IS_ACTIVE, Nullable<System.DateTime> p_ASSIGNED_DATE)
        {
            var p_USER_IDParameter = p_USER_ID.HasValue ?
                new ObjectParameter("P_USER_ID", p_USER_ID) :
                new ObjectParameter("P_USER_ID", typeof(int));
    
            var p_PROJECT_IDParameter = p_PROJECT_ID.HasValue ?
                new ObjectParameter("P_PROJECT_ID", p_PROJECT_ID) :
                new ObjectParameter("P_PROJECT_ID", typeof(int));
    
            var p_IS_ACTIVEParameter = p_IS_ACTIVE.HasValue ?
                new ObjectParameter("P_IS_ACTIVE", p_IS_ACTIVE) :
                new ObjectParameter("P_IS_ACTIVE", typeof(bool));
    
            var p_ASSIGNED_DATEParameter = p_ASSIGNED_DATE.HasValue ?
                new ObjectParameter("P_ASSIGNED_DATE", p_ASSIGNED_DATE) :
                new ObjectParameter("P_ASSIGNED_DATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPD_USER_PROJECT_PR", p_USER_IDParameter, p_PROJECT_IDParameter, p_IS_ACTIVEParameter, p_ASSIGNED_DATEParameter);
        }
    }
}
