--Table creation

DROP TABLE TBL_USER;
CREATE TABLE TBL_USER
(
	[ID] INT NOT NULL PRIMARY KEY,
	[FIRST_NAME] NVARCHAR(50) NOT NULL,
	[LAST_NAME] NVARCHAR(50) NOT NULL
)
GO;

DROP TABLE TBL_PROJECT;
CREATE TABLE TBL_PROJECT
(
	[ID] INT NOT NULL PRIMARY KEY,
	[START_DATE] DATETIME NOT NULL,
	[END_DATE] DATETIME NOT NULL,
	[CREDITS] INT NOT NULL
)
GO;

DROP TABLE TBL_USER_PROJECT;
CREATE TABLE TBL_USER_PROJECT
(
	[USER_ID] INT NOT NULL REFERENCES TBL_USER,
	[PROJECT_ID] INT NOT NULL REFERENCES TBL_PROJECT,
	[IS_ACTIVE] BIT NOT NULL,
	[ASSIGNED_DATE] DATETIME NOT NULL
)
GO;

-- User table stored procedures
-- User creation 

CREATE OR ALTER PROCEDURE CRE_USER_PR
	@P_ID INT,
	@P_FIRST_NAME NVARCHAR(50),
	@P_LAST_NAME NVARCHAR(50)
AS
	INSERT INTO TBL_USER
VALUES
(
	@P_ID,
	@P_FIRST_NAME,
	@P_LAST_NAME
);
GO;

--Retrieve all users
CREATE OR ALTER PROCEDURE RET_ALL_USERS_PR
AS
	SELECT * FROM TBL_USER;
RETURN 0
GO;

-- Retrieve user by id
CREATE OR ALTER PROCEDURE RET_USER_PR
	@P_USER_ID INT
AS
	SELECT FIRST_NAME, LAST_NAME 
	FROM TBL_USER
	WHERE ID = @P_USER_ID;
RETURN 0
GO;

-- Update user
CREATE OR ALTER PROCEDURE UPD_USER_PR
	@P_ID INT,
	@P_FIRST_NAME NVARCHAR(50),
	@P_LAST_NAME NVARCHAR(50)
AS
	UPDATE TBL_USER
	SET FIRST_NAME = @P_FIRST_NAME,
	LAST_NAME = @P_LAST_NAME
	WHERE ID = @P_ID;
GO;
	
-- Delete user
CREATE OR ALTER PROCEDURE DEL_USER_PR
	@P_ID INT
AS
	DELETE FROM TBL_USER
	WHERE ID = @P_ID;
RETURN 0
GO;

-- Project procedures
-- Create project
CREATE OR ALTER PROCEDURE CRE_PROJECT_PR
	@P_ID INT,
	@P_START_DATE DATETIME,
	@P_END_DATE DATETIME,
	@P_CREDITS INT
AS
	INSERT INTO TBL_PROJECT
	VALUES
	(
		@P_ID,
		@P_START_DATE,
		@P_END_DATE,
		@P_CREDITS
	);
GO;

-- Retrieve all projects
CREATE OR ALTER PROCEDURE RET_ALL_PROJECTS_PR
AS
	SELECT * FROM TBL_PROJECT;
RETURN 0
GO;

-- Retrieve by id
CREATE OR ALTER PROCEDURE RET_PROJECT_PR
	@P_ID INT
AS
	SELECT START_DATE, END_DATE, CREDITS
	FROM TBL_PROJECT
	WHERE ID = @P_ID;
RETURN 0
GO;

-- Update project
CREATE OR ALTER PROCEDURE UPD_PROJECT_PR
	@P_ID INT,
	@P_START_DATE DATETIME,
	@P_END_DATE DATETIME,
	@P_CREDITS INT
AS
	UPDATE TBL_PROJECT
	SET START_DATE = @P_START_DATE,
	END_DATE = @P_END_DATE,
	CREDITS = @P_CREDITS
	WHERE ID = @P_ID;
GO;

-- Delete project
CREATE OR ALTER PROCEDURE DEL_PROJECT_PR
	@P_ID INT
AS
	DELETE FROM TBL_PROJECT
	WHERE ID = @P_ID;
RETURN 0
GO;

-- UserProject procedures
-- Create user project
CREATE OR ALTER PROCEDURE CRE_USER_PROJECT_PR
	@P_USER_ID INT,
	@P_PROJECT_ID INT,
	@P_ASSIGNED_DATE DATETIME
AS
	INSERT INTO TBL_USER_PROJECT
	VALUES
	(
		@P_USER_ID,
		@P_PROJECT_ID,
		1,
		@P_ASSIGNED_DATE
	)
RETURN 0
GO;

-- Retrieve all user projects
CREATE OR ALTER PROCEDURE RET_ALL_USER_PROJECTS_PR
AS
	SELECT * FROM TBL_USER_PROJECT;
RETURN 0
GO;

-- Retrieve user project by id
CREATE OR ALTER PROCEDURE RET_USER_PROJECT_PR
	@P_USER_ID INT,
	@P_PROJECT_ID INT
AS
	SELECT IS_ACTIVE, ASSIGNED_DATE 
	FROM TBL_USER_PROJECT 
	WHERE USER_ID = @P_USER_ID
	AND PROJECT_ID = @P_PROJECT_ID;
RETURN 0
GO;

-- Update user project
CREATE OR ALTER PROCEDURE UPD_USER_PROJECT_PR
	@P_USER_ID INT,
	@P_PROJECT_ID INT,
	@P_IS_ACTIVE BIT,
	@P_ASSIGNED_DATE DATETIME
AS
	UPDATE TBL_USER_PROJECT
	SET IS_ACTIVE = @P_IS_ACTIVE,
	ASSIGNED_DATE = @P_ASSIGNED_DATE
	WHERE USER_ID = @P_USER_ID
	AND PROJECT_ID = @P_PROJECT_ID;
GO;

-- Delete user project
CREATE OR ALTER PROCEDURE DEL_USER_PROJECT_PR
	@P_USER_ID INT,
	@P_PROJECT_ID INT
AS
	DELETE FROM TBL_USER_PROJECT
	WHERE USER_ID = @P_USER_ID
	AND PROJECT_ID = @P_PROJECT_ID;
GO;